version: "3.9"
services:
  frontend:
    build:
      context: ./DREANK/DREANK
      dockerfile: DREANK_BACK-back/Dockerfile
    container_name: dreank_frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./DREANK_BACK
      dockerfile: DREANK_BACK-back/Dockerfile
    container_name: dreank_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://144.24.69.9.3:3306/dreank_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kimhy119@
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
