version: "3.9"
services:
  frontend:
    image: frontend-image:latest
    build:
      context: ./DREANK/DREANK
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: backend-image:latest
    build:
      context: ./DREANK_BACK
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dreank_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kimhy119@
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kimhy119@
      MYSQL_DATABASE: dreank_test
      MYSQL_USER: root
      MYSQL_PASSWORD: kimhy119@
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
